import { Product } from '../types/product';

function daysAgo(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
}

export function buildSeedProducts(): Product[] {
  return [
    {
      id: 'seed-1',
      name: 'Riz basmati 1kg',
      reference: 'ALM-001',
      description: 'Sac de riz basmati, origine Inde.',
      category: 'Alimentaire',
      quantity: 42,
      alertThreshold: 15,
      createdAt: daysAgo(30),
      updatedAt: daysAgo(2),
    },
    {
      id: 'seed-2',
      name: 'Café moulu 250g',
      reference: 'ALM-002',
      description: 'Café arabica torréfaction moyenne.',
      category: 'Alimentaire',
      quantity: 6,
      alertThreshold: 10,
      createdAt: daysAgo(30),
      updatedAt: daysAgo(1),
    },
    {
      id: 'seed-3',
      name: 'Pâtes penne 500g',
      reference: 'ALM-003',
      description: 'Pâtes de blé dur, format penne.',
      category: 'Alimentaire',
      quantity: 0,
      alertThreshold: 12,
      createdAt: daysAgo(28),
      updatedAt: daysAgo(4),
    },
    {
      id: 'seed-4',
      name: 'Eau minérale 1.5L',
      reference: 'BOI-001',
      description: 'Pack de 6 bouteilles.',
      category: 'Boissons',
      quantity: 58,
      alertThreshold: 20,
      createdAt: daysAgo(25),
      updatedAt: daysAgo(3),
    },
    {
      id: 'seed-5',
      name: "Jus d'orange 1L",
      reference: 'BOI-002',
      description: 'Jus d\'orange 100% pur jus.',
      category: 'Boissons',
      quantity: 9,
      alertThreshold: 10,
      createdAt: daysAgo(25),
      updatedAt: daysAgo(1),
    },
    {
      id: 'seed-6',
      name: 'Savon liquide 500ml',
      reference: 'HYG-001',
      description: 'Savon liquide pour les mains, parfum neutre.',
      category: 'Hygiène',
      quantity: 24,
      alertThreshold: 8,
      createdAt: daysAgo(20),
      updatedAt: daysAgo(6),
    },
    {
      id: 'seed-7',
      name: 'Dentifrice menthe 75ml',
      reference: 'HYG-002',
      description: 'Dentifrice fluoré, protection caries.',
      category: 'Hygiène',
      quantity: 0,
      alertThreshold: 6,
      createdAt: daysAgo(20),
      updatedAt: daysAgo(9),
    },
    {
      id: 'seed-8',
      name: 'Éponges (lot de 6)',
      reference: 'ENT-001',
      description: 'Éponges double face pour vaisselle.',
      category: 'Entretien',
      quantity: 33,
      alertThreshold: 10,
      createdAt: daysAgo(18),
      updatedAt: daysAgo(5),
    },
    {
      id: 'seed-9',
      name: 'Lessive liquide 3L',
      reference: 'ENT-002',
      description: 'Lessive liquide, 40 doses environ.',
      category: 'Entretien',
      quantity: 4,
      alertThreshold: 5,
      createdAt: daysAgo(18),
      updatedAt: daysAgo(2),
    },
    {
      id: 'seed-10',
      name: 'Désinfectant multi-surfaces',
      reference: 'ENT-003',
      description: 'Spray désinfectant 750ml.',
      category: 'Entretien',
      quantity: 17,
      alertThreshold: 8,
      createdAt: daysAgo(15),
      updatedAt: daysAgo(7),
    },
    {
      id: 'seed-11',
      name: 'Cahier A4 96 pages',
      reference: 'PAP-001',
      description: 'Cahier grands carreaux, couverture polypro.',
      category: 'Papeterie',
      quantity: 65,
      alertThreshold: 20,
      createdAt: daysAgo(12),
      updatedAt: daysAgo(1),
    },
    {
      id: 'seed-12',
      name: 'Stylo bille bleu (boîte de 50)',
      reference: 'PAP-002',
      description: 'Stylos bille pointe moyenne.',
      category: 'Papeterie',
      quantity: 3,
      alertThreshold: 5,
      createdAt: daysAgo(12),
      updatedAt: daysAgo(3),
    },
  ];
}
